### ISSUE TITLE
missing blacklist filtering?

### ISSUE THREAD

**Issue by funnell** [shahcompbio/wgs#1]
is mappability filtering still done?

**Comment by diljotgrewal** [comment]
v0.x flags the positions. It does not filter them out.

**Comment by funnell** [comment]
Is this a new change or has it always been like this?

**Comment by diljotgrewal** [comment]
from v0.0.1-0.0.4 it was filtered out.

v0.0.5 -v0.0.x flags low mappability calls.

we're redoing variant calling from scratch with v0.1.x and we haven't spec'd it out completely yet. I'll keep you posted.

**Comment by funnell** [comment]
The IGO and SPECTRUM results I've grabbed from your directory... which version were those generated with?

**Comment by diljotgrewal** [comment]
those should be flagged.

**Comment by funnell** [comment]
uh oh.
